server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/foodtracker_server_prod?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: my_secret_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  data:
    mongodb:
      host: mongo_config
      port: 27017
      password: bt2e54KGbh
      database: foodtracker
      username: dpajak99
      authentication-database: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
foodtracker:
  app:
    url: https://api.foodtracker.pl
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    storage-absolute-path: /opt/static